name: Generate activity graph

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v6

      - name: generate activity-graph.svg
        uses: maurodesouza/github-readme-activity-graph-action@v1
        with:
          username: ${{ github.repository_owner }}
          options: radius=16&theme=dracula&area=true&height=300
          output_path: dist/activity-graph.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: push activity-graph.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: activity-graph-output
          build_dir: dist
          author: "Guilherme Beserra <173941502+GuiCodeLabs@users.noreply.github.com>"
          committer: "Guilherme Beserra <173941502+GuiCodeLabs@users.noreply.github.com>"
          commit_message: "chore(activity): atualiza gráfico de atividade"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}